version: "3.9"
services:
  sim:
    build:
      context: .
      dockerfile: Dockerfile
      target: sim
    user: "${FIXUID:?}:${FIXGID:?}"
    volumes:
      - .:/workspace
    devices:
      # Required for VirtualGL
      - /dev/dri:/dev/dri
    ports:
      - "15900:5900" # VMC
      - "18765:8765" # Foxglove
      - "5678:5678" # Debugpy
  robot:
    build:
      context: .
      dockerfile: Dockerfile
      target: robot
    user: "${FIXUID:?}:${FIXGID:?}"
    volumes:
      - .:/workspace
    devices:
      - /dev/jackal:/dev/jackal
      - /dev/input/ps4:/dev/input/ps4
      - /dev/clearpath/um7:/dev/clearpath/um7
    network_mode: "host"