version: "3.9"
services:
  sim:
    build:
      context: .
      dockerfile: Dockerfile
      target: sim
    user: "${FIXUID:?}:${FIXGID:?}"
    volumes:
      - .:/workspace
    devices:
      # Required for VirtualGL
      - /dev/dri:/dev/dri
    ports:
      - "15900:5900" # VMC
      - "18765:8765" # Foxglove
  robot:
    build:
      context: .
      dockerfile: Dockerfile
      target: robot
    user: "${FIXUID:?}:${FIXGID:?}"
    volumes:
      - .:/workspace
      - /dev/jackal:/dev/jackal
    network_mode: "host"