version: "3.9"
services:
  dev:
    build: .
    user: "${FIXUID:?}:${FIXGID:?}"
    volumes:
      - .:/workspace
    devices:
      # Required for VirtualGL
      - /dev/dri:/dev/dri
    ports:
      - "15900:5900" # VMC