bdetect:
  model_type: "DIFFERENTIAL_DRIVE"
  N: 5 # The measurement window size (the number of timesteps)
  dt: 0.1 # The discretization timestep of the model. Sensor measurements are sampled at this rate.
  sensors:
    - topic: "/global_localization/robot/odom"
      type: "ODOMETRY"
      measured_states:
        - "X"
        - "Y"
        - "ORIENTATION"
    - topic: "/jackal_velocity_controller/odom"
      type: "ODOMETRY"
      measured_states:
        - "VELOCITY"
    - topic: "/imu/data"
      type: "IMU"
      measured_states:
        - "ANGULAR_VELOCITY"
