bdetect:
  model_type: "DIFFERENTIAL_DRIVE"
  N: 20 # The measurement window size (the number of timesteps)
  dt: 0.1 # The discretization timestep of the model. Sensor measurements are sampled at this rate.
  solve_frame: "odom" # The frame in which the solver operates
  sensors:
    - name: "global_odometry"
      topic: "/global_localization/robot/odom/vulnerable"
      type: "ODOMETRY"
      measured_states:
        - "X"
        - "Y"
        - "ORIENTATION"
      transform_to_solve_frame: true
    - name: "local_odometry"
      topic: "/jackal_velocity_controller/odom/vulnerable"
      type: "ODOMETRY"
      measured_states:
        - "VELOCITY"
        - "ANGULAR_VELOCITY"
    - name: "imu"
      topic: "/bbase/imu/data"
      type: "IMU"
      measured_states:
        - "ANGULAR_VELOCITY"
  inputs:
    - name: "cmd_vel"
      topic: "/jackal_velocity_controller/cmd_accel_out"
      type: "ACCEL_STAMPED"
      measured_inputs:
        - "ACCELERATION"
        - "ANGULAR_ACCELERATION"
