frequency: 100

# odometry from the wheel encoders
odom0: /jackal_velocity_controller/odom
odom0_config: [
  false, false, false, # x, y, z
  false, false, false, # roll, pitch, yaw
  true, true, true, # vx, vy, vz
  false, false, true, # vroll, vpitch, vyaw
  false, false, false # ax, ay, az
]
odom0_differential: false

# Global odometry
odom1: /global_localization/robot/odom
odom1_config: [
  true, true, false, # x, y, z
  false, false, true, # roll, pitch, yaw
  false, false, false, # vx, vy, vz
  false, false, false, # vroll, vpitch, vyaw
  false, false, false # ax, ay, az
]
odom1_differential: false

imu0: /imu/data
imu0_config: [
  false, false, false, # x, y, z
  true, true, false, # roll, pitch, yaw
  false, false, false, # vx, vy, vz
  true, true, true, # vroll, vpitch, vyaw
  false, false, false # ax, ay, az
]
imu0_differential: false

odom_frame: odom
base_link_frame: base_link
map_frame: map
world_frame: map

predict_to_current_time: true
two_d_mode: true