frequency: 50

# odometry from the wheel encoders
odom0: /jackal_velocity_controller/odom
odom0_config: [
  false, false, false, # x, y, z
  false, false, false, # roll, pitch, yaw
  true, true, true, # vx, vy, vz
  false, false, true, # vroll, vpitch, vyaw
  false, false, false # ax, ay, az
]
odom0_differential: false

imu0: /imu_um7/data
imu0_config: [
  false, false, false, # x, y, z
  true, true, false, # roll, pitch, yaw
  false, false, false, # vx, vy, vz
  true, true, true, # vroll, vpitch, vyaw
  false, false, false # ax, ay, az
]
imu0_differential: false

odom_frame: odom
base_link_frame: base_link
world_frame: odom

predict_to_current_time: true