name: Run tests

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  run_tests:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:focal
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - uses: docker/build-push-action@v4
        with:
          tags: benz/research-jackal
          cache-from: type=gha
      - run: |
          pwd
          ls -alh
          docker images ls
          docker ps
          #cd catkin_ws
          #rosdep install --from-paths src --ignore-src -r -y
          #python3 ./src/bcontrol/src/utils.py
