name: Run tests

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

concurrency: ci-${{ github.ref }}

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      # necessary for buildx cache:
      # https://docs.docker.com/build/cache/backends/gha/#authentication
      - name: Expose GitHub Runtime
        uses: crazy-max/ghaction-github-runtime@v2
      - run: |
          docker buildx build --cache-to=type=gha --cache-from=type=gha -t benz/research-jackal --output type=docker .
          docker run -v $(pwd):/workspace benz/research-jackal bash -c "source /opt/ros/noetic/setup.bash && cd /workspace/catkin_ws && rosdep install --from-paths src --ignore-src -r -y && python3 ./src/bcontrol/src/utils.py"
