name: Run tests

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - run: |
          pwd
          ls -alh
          docker images ls
          docker ps
          docker buildx build --cache-to=type=gha --cache-from=type=gha -t benz/research-jackal .
          #cd catkin_ws
          #rosdep install --from-paths src --ignore-src -r -y
          #python3 ./src/bcontrol/src/utils.py
