name: Run tests

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

concurrency: ci-${{ github.ref }}

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      # Free up disk space:
      # https://github.com/actions/runner-images/issues/10386#issuecomment-2270874323
      - name: Free Disk Space Before Build
        run: |
          echo "Disk space before cleanup:"
          df -h
          sudo rm -rf /usr/local/.ghcup
          sudo rm -rf /opt/hostedtoolcache/CodeQL
          sudo rm -rf /usr/local/lib/android/sdk/ndk
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/local/share/boost
          sudo apt-get clean
          echo "Disk space after cleanup:"
          df -h
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      # necessary for buildx cache:
      # https://docs.docker.com/build/cache/backends/gha/#authentication
      - name: Expose GitHub Runtime
        uses: crazy-max/ghaction-github-runtime@v2
      - name: Run tests using the `robot` target
        run: |
          docker buildx build --cache-to=type=gha --cache-from=type=gha --target=robot -t benz/research-jackal-robot --output type=docker .
          docker run --rm -u $(id -u):$(id -g) -v $(pwd):/workspace benz/research-jackal-robot bash -c "source /etc/local.bashrc && devsetup && rosdep_install_all && catkin build && devsetup && ../run_tests.sh"
      - name: Run tests using the `sim` target
        run: |
          docker buildx build --cache-to=type=gha --cache-from=type=gha --target=sim -t benz/research-jackal-sim --output type=docker .
          docker run --rm -u $(id -u):$(id -g) -v $(pwd):/workspace benz/research-jackal-sim bash -c "source /etc/local.bashrc && devsetup && rosdep_install_all && catkin build && devsetup && ../run_tests.sh"
